stages:
  train:
    cmd: python train.py
    deps:
    - train.py
    metrics:
    - metrics.txt:
        cache: false
    plots:
  # Data series source
    - classes.csv:
        # Configure template and axes.
        template: confusion
        x: actual
        y: predicted

    
